name: 'Install Python Dependencies'
description: 'GitHub Action to install Python dependencies using PIP'
author: 'insightiq'
inputs:
  requirements-file:
    description: 'Path to the requirements file'
    required: true
    default: 'requirements.txt'

runs:
  using: 'docker'
  image: './Dockerfile'

branding:
  icon: 'package'
  color: 'blue'
