---

- name: Deploy to Production
  hosts: localhost
  tasks:
    - name: Pull Redis image
      command: sudo docker pull redis

    - name: Pull Web App image
      command: sudo docker pull athuls121/web_app_fe:latest

    - name: Running Docker Compose file
      command: sudo docker-compose down && sudo docker-compose up
