name: Unit Test and Build Checks

on: [push, pull_request]

# declaring global env variables
env:
  USERNAME: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}


jobs:
  Build_Checks_and_Unit_Tests:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

# Using CUSTOM ACTIONS to install the requirements namely Python modules
        - name: Install dependencies
          uses: ./  
          with:
            requirements-file: 'requirements.txt'  

        - name: Run Unit Tests
          run: python test_app.py 2>&1 | tee test-report.txt

        - name: Run the web_app - FrontEndweb_app_fe
          run: |
               docker build -t athuls121/web_app_fe:latest .  
               docker run --rm -d --name web_app -p 8080:8080 athuls121/web_app_fe:latest

        - name: Wait for Application to start
          run: |
            sleep 3
            docker ps

        - name: Archive test report
          uses: actions/upload-artifact@v2
          with:
            name: test-report
            path: test-report.txt

        - name: web_app Image Push
          run: |
              # Push the Docker image to GitHub Packages
              echo "${{ secrets.DOCKERHUB_PWD }}" | docker login -u athuls121 --password-stdin 
              docker push athuls121/web_app_fe:latest
