name: Code Testing

on: [push, pull_request]

# declaring global env variables
env:
  USERNAME: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  IMAGE_NAME: ica2_image
  TAG: v1


jobs:
  code_testing:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run the redis - BackEnd
          run: |
              docker image pull redis:latest
              docker image tag redis:latest docker.pkg.github.com/athuls121/github-actions-project/redis_be:v1
              docker run --rm -d --name redis -p 6379:6379 docker.pkg.github.com/athuls121/github-actions-project/redis_be:v1
              docker ps

        - name: Run the web_app - FrontEnd
          run: |
              ls -a
              docker build -t docker.pkg.github.com/athuls121/github-actions-project/web_app_fe:v1 .  
              docker run --rm -d --name web_app -p 8080:8080 docker.pkg.github.com/athuls121/github-actions-project/web_app_fe:v1
              docker ps

        - name: Verify web application using CURL
          run: |
              docker exec web_app curl http://localhost:8080

        - name: Wait for app to start
          run: sleep 10

        - name: Run Tests
          run: python test_app.py 2>&1 | tee test-report.txt


        - name: Archive test report
          uses: actions/upload-artifact@v2
          with:
            name: test-report
            path: test-report.txt

        - name: web_app Image Push
          run: |
            #Authenticate to GitHub Packages using secret
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u athuls121 --password-stdin
            # Push the Docker image to GitHub Packages
              docker push docker.pkg.github.com/athuls121/github-actions-project/redis_be:v1

        - name: redis Image Push
          run: |
            #Authenticate to GitHub Packages using secret
              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login docker.pkg.github.com -u athuls121 --password-stdin
            # Push the Docker image to GitHub Packages
              docker push docker.pkg.github.com/athuls121/github-actions-project/web_app_fe:v1

