name: Deploy Testing Env

on:
  workflow_run:
    workflows: ["Unit Test and Build Checks"]
    types:
      - completed

# declaring global env variables
env:
  USERNAME: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}

  DOCKER_REPO: ${{ secrets.DOCKER_REPO }}   #DockerHub Repo


jobs:
  Deployed_over_Testing_Environment:
    runs-on: ubuntu-latest

# Workflow Condition
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

# creating seperate Testing Environment in GitHub
    environment: Testing Environment    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

# Using CUSTOM ACTIONS to install the requirements namely Python modules
      - name: Install dependencies
        uses: ./  
        with:
          requirements-file: 'requirements.txt'  

      - name: Run the redis - BackEnd
        run: |
            docker image pull redis:latest
            docker run --rm -d --name redis -p 6379:6379 redis


      - name: Run the web_app - FrontEnd
        run: |
            docker image pull athuls121/web_app_fe:latest
            docker run --rm -d --name web_app -p 8080:8080 ${{ env.DOCKER_REPO }}/web_app_fe:latest

      - name: Wait for Application to start
        run: |
            sleep 3
            docker ps

# Verification of the application using CURL
      - name: Verify Web Application using CURL
        run: |
            curl http://localhost:8080 2>&1 | tee app-verification.txt

      - name: Archive App Verification Report
        uses: actions/upload-artifact@v2
        with:
          name: App-Verification
          path: app-verification.txt
