name: Deploy Production Env

on:
  workflow_run:
    workflows: ["Deploy Testing Env"]
    types:
      - completed
      
# declaring global env variables
env:
    USERNAME: ${{ github.repository_owner }}
    REPOSITORY: ${{ github.event.repository.name }}
  
    HOST: ${{ secrets.EC2_HOST }}                     #SSH Future Works
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}   #SSH Future Works

jobs:
  Deployed_over_Production_Environment:
    runs-on: self-hosted                              #AWS EC2 Instance

# Workflow Condition
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

# creating seperate Production Environment in GitHub
    environment: Production Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

# Executing the Ansible Playbook for Production Deployment 
      - name: Show playbook content
        run: |
              cat playbook.yml  
  
      - name: Run Ansible playbook
        run: |
              ansible-playbook playbook.yml

      - name: Verify Web Application using CURL
        run: |
            sleep 2s
            sudo curl http://localhost:8080
