name: Deploy Production Env

on:
  workflow_run:
    workflows: ["Deploy Testing Env"]
    types:
      - completed

# declaring global env variables
env:
    USERNAME: ${{ github.repository_owner }}
    REPOSITORY: ${{ github.event.repository.name }}
  
    IMAGE_NAME_DB: ${{ secrets.IMAGE_NAME_DB }}
    IMAGE_NAME_APP: ${{ secrets.IMAGE_NAME_APP }}
    TAG: ${{ secrets.TAG }}
  
    HOST: ${{ secrets.EC2_HOST }}
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  Linux-self-hosted:
    runs-on: self-hosted

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment: Production Environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Show playbook content
        run: |
              cat playbook.yml  
  
      - name: Run Ansible playbook
        run: |
              ansible-playbook playbook.yml

      - name: Verify web application using CURL
        run: |
            sleep 5s
            docker ps
            curl http://localhost:8080
