name: Deploy Testing Env

on:
  workflow_run:
    workflows: ["Unit Test and Build Checks"]
    types:
      - completed

# declaring global env variables
env:
  USERNAME: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}


jobs:
  deploy_testing:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}    #creating seperating environment in GitHub

    environment: Testing Environment    #creating seperate Test Environment in GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the redis - BackEnd
        run: |
            docker image pull redis:latest
            docker run --rm -d --name redis -p 6379:6379 redis


      - name: Run the web_app - FrontEnd
        run: |
            docker image pull athuls121/web_app_fe:v1
            docker run --rm -d --name web_app -p 8080:8080 athuls121/web_app_fe:v1


      - name: Verify web application using CURL
        run: |
            sleep 5s
            docker ps
            curl http://localhost:8080

      - name: Wait for unit test to start
        run: sleep 10

      - name: Run Tests
        run: python test_app.py 2>&1 | tee test-report.txt

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report-TestEnv
          path: test-report-TestEnv.txt
