name: CI/CD

on: [push, pull_request]

env:
  USERNAME: ${{ github.repository_owner }}
  REPOSITORY: ${{ github.event.repository.name }}
  IMAGE_NAME: ica2_image
  TAG: v1

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      web-app:
        image: python:3.9
        ports:
          - 8080:8080
        env:
          REDIS_HOST: redis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Wait for services to start
        run: sleep 10

      - name: Install dependencies and run the application
        run: |
          pip install -r requirements.txt
          python app.py

      - name: Run Tests
        run: python test_app.py
