name: CI/CD

on: [push, pull_request]

jobs:
  python_unit_tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

        # #Using CUSTOM ACTIONS to install the requirements namely Python modules
      - name: Install dependencies
        uses: athuls121/github-actions-project@main
        with:
          requirements-file: 'requirements.txt' 


      - name: Run unit tests and generate text report
        run: |
          python test_app.py 2>&1 | tee test-report.txt
